[project]
name = "hooks"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pydantic>=2.9.2",
    "sqlmodel>=0.0.22",
    "typer>=0.12.5",
]
