# Show hidden files by default
default_flags = "-h"

# Display options
show_selection_mark = true

# Search settings
content_search_max_file_size = "10MB"

# Preview settings
lines_before_match_in_preview = 1
lines_after_match_in_preview = 1

# Keyboard settings
enable_kitty_keyboard = false

# Special path configurations
[special-paths]
"/media" = { list = "never", sum = "never" }
"~/.config" = { show = "always" }
"trav" = { show = "always", list = "always", sum = "never" }

# Search mode configurations
[search-modes]
"<empty>" = "fuzzy name" # Fixed search mode
"/" = "regex path"       # Fixed search mode
"c/" = "regex content"   # Fixed search mode

# Import verb configurations
[[imports]]
file = "verbs.toml"

# Import theme based on terminal luminance
[[imports]]
luma = ["dark", "unknown"]
file = "skins/catppuccin-mocha.toml"

[[imports]]
luma = "light"
file = "skins/white.toml"
