###############################################################
# Navigation and Core Actions
###############################################################
[[verbs]]
key = "ctrl-p"
internal = ":toggle_preview"

[[verbs]]
invocation = "toggle_tree"
key = "ctrl-t"
internal = ":toggle_tree"

[[verbs]]
key = "alt-h"
internal = ":toggle_hidden"

[[verbs]]
key = "alt-i"
internal = ":toggle_git_ignore"

[[verbs]]
key = "alt-c"
internal = ":copy_line"

###############################################################
# Basic Navigation
###############################################################
[[verbs]]
key = "up"
internal = ":line_up"

[[verbs]]
key = "down"
internal = ":line_down"

[[verbs]]
key = "home"
internal = ":select_first"

[[verbs]]
key = "end"
internal = ":select_last"

[[verbs]]
key = "pgup"          # Fixed from page-up
internal = ":page_up"

[[verbs]]
key = "pgdown"          # Fixed from page-down
internal = ":page_down"

###############################################################
# Panel Management
###############################################################
[[verbs]]
key = "ctrl-left"
internal = ":panel_left"

[[verbs]]
key = "ctrl-right"
internal = ":panel_right"

###############################################################
# File Opening and Editing
###############################################################
[[verbs]]
invocation = "default_enter"
key = "enter"
external = "nvim +{line} {file}"
apply_to = "text_file"
leave_broot = false

[[verbs]]
invocation = "default_enter_dir"
key = "enter"
internal = ":focus"
apply_to = "directory"

[[verbs]]
invocation = "edit"
shortcut = "e"
key = "ctrl-e"
apply_to = "text_file"
external = "nvim {file}"
leave_broot = false

[[verbs]]
invocation = "create {subpath}"
external = "nvim {directory}/{subpath}"
leave_broot = false

###############################################################
# File Operations
###############################################################
[[verbs]]
invocation = "mkdir"
shortcut = "md"
external = "mkdir -p {directory}/{subpath}"
leave_broot = false

[[verbs]]
invocation = "delete"
shortcut = "rm"
external = "rm -rf {file}"
leave_broot = false

[[verbs]]
invocation = "cp {subpath}"
shortcut = "cp"
external = "cp -r {file} {subpath}"
leave_broot = false

[[verbs]]
invocation = "move {subpath}"
shortcut = "mv"
external = "mv {file} {subpath}"
leave_broot = false

[[verbs]]
invocation = "chmod {args}"
shortcut = "ch"
external = "chmod {args} {file}"
leave_broot = false

[[verbs]]
invocation = "backup {version}"
key = "ctrl-b"
leave_broot = false
auto_exec = false
external = "cp -r {file} {parent}/{file-stem}-{version}{file-dot-extension}"

###############################################################
# Panel Operations
###############################################################
[[verbs]]
invocation = "copy_to_panel"
key = "F5"
shortcut = "cpp"
external = "cp -r {file} {other-panel-directory}"
leave_broot = false

[[verbs]]
invocation = "move_to_panel"
key = "F6"
shortcut = "mvp"
external = "mv {file} {other-panel-directory}"
leave_broot = false

###############################################################
# Git Operations
###############################################################
[[verbs]]
key = "alt-g"
internal = ":toggle_git_file_info"

[[verbs]]
invocation = "git_diff"
shortcut = "gd"
external = "git difftool -y {file}"
leave_broot = false

###############################################################
# Terminal
###############################################################
[[verbs]]
invocation = "terminal"
key = "ctrl-t"
external = "$SHELL"
set_working_dir = true
leave_broot = false

###############################################################
# Search and Select
###############################################################
[[verbs]]
key = "ctrl-s"
internal = ":search_again"

[[verbs]]
key = "ctrl-f"
internal = ":focus"

[[verbs]]
key = "tab"
internal = ":next_match"

###############################################################
# View Toggles
###############################################################
[[verbs]]
key = "alt-s"
internal = ":toggle_sizes"

[[verbs]]
key = "alt-d"
internal = ":toggle_dates"

[[verbs]]
key = "alt-p"
internal = ":toggle_perm"

###############################################################
# General Actions
###############################################################
[[verbs]]
key = "ctrl-q"
internal = ":quit"

[[verbs]]
key = "F1"
internal = ":help"
