[[database]]
Name = 'taskwarrior'
Provider = 'sqlite3'
DBName = ''
URL = '/Users/yuvalspiegel/.taskwarrior/taskchampion.sqlite3'

[[database]]
Name = 'treex-bagfile1'
Provider = 'sqlite3'
DBName = ''
URL = '/Users/yuvalspiegel/treex-mono/data/treex/datasets/raw_data/bag_recordings/qube_eye_100/rec_jetson8_2024-11-28_02-03-06.bag/rec_jetson8_2024-11-28_02-03-06.bag_0.db3'
