# Espanso base configuration
# This file now contains only the base setup
# Specific snippets are organized in separate files:
# - git.yml: Git and conventional commits
# - implementation.yml: Implementation strategies and planning
# - learning.yml: Learning and understanding helpers
# - files.yml: File and code management
# - misc.yml: Miscellaneous snippets

matches:
  # Add any common snippets here that don't fit in other categories