# Espanso configuration
# Place this file at: ~/.config/espanso/match/base.yml

matches:
  # First Principles
  - trigger: ":first"
    replace: "explain from first principles"
    label: "first principles"

  # Conventional Commits
  - trigger: ":cv"
    replace: "conventional commits"
    label: "conventional commits"

  - trigger: ":cf"
    replace: "suggest git commit according to conventional commits\n\n\n"
    label: "conventional commit full"

  - trigger: ":cc"
    replace: "suggest git commit message according to conventional commits"
    label: "conventional commits full"

  - trigger: ":cl"
    replace: "suggest one line git commit according to conventional commits. put it in code block.\n"
    label: "conventional commits one line"

  # Implementation Strategies
  - trigger: ":ways"
    replace: "then ill choose and you'll implement"
    label: "then ill choose and you'll implement"

  - trigger: ":suggest1"
    replace: "suggest a couple of strategies and ill choose one "
    label: "suggest1"

  - trigger: ":suggest2"
    replace: "look at the code and suggest a couple of strategies to modify it in order to implement the desired behavior. then ill choose one of your options and youll implement it"
    label: "suggest2"

  - trigger: ":suggest3"
    replace: "suggest a couple of strategies how to do it and ill choose one\n"
    label: "suggest3"

  - trigger: ":preview"
    replace: "preview the way you think about implementing this then if i approve you'll implement it"
    label: "preview"

  - trigger: ":plan"
    replace: "explain how you are planning to do it first. then if i confirm we will continue.\n"
    label: "plan"

  - trigger: ":mp"
    replace: "make a plan first"
    label: "make a plan first"

  # Reading and Understanding
  - trigger: ":readit"
    replace: "read it carefully and then i'll ask you to help with improving it"
    label: "readit"

  - trigger: ":exp1"
    replace: "explain the task so i know you understood"
    label: "explain the task so i know you understood"

  - trigger: ":du"
    replace: "do you understand"
    label: "do you undetstand"

  - trigger: ":un"
    replace: "i don't understand"
    label: "i dont understand copy"

  - trigger: ":uf"
    replace: "i don't fucking understand"

  - trigger: ":sl1"
    replace: "start from the beginning and move in very slow steps. dont move to next step until i approve"
    label: "important - start from the beginning and move in very slow steps"

  - trigger: ":sl0"
    replace: "explain slowly"

  - trigger: ":sm1"
    replace: "move in very slow and small steps. dont move to next step until i approve"
    label: "important - move in very slow and small steps"

  - trigger: ":sm0"
    replace: "small steps"
    label: "small steps"

  - trigger: ":cn"
    replace: "continue"

  - trigger: ":care"
    replace: "read this tutorial very carefully. this is pdf so it's not very structured so please read it again and again and again in order to make sure you understand it all. ask yourself if you understood everything to make sure and read again to make sure you indeed he indeed understood"
    label: "important - read this tutorial very carefully"

  - trigger: ":app"
    replace: "dont move to next step until i approve"
    label: "important - dont move to next step until i approve"

  - trigger: ":new"
    replace: "this is question 1 (about LR) of the homework. i want to solve it in the same way we solve question 2 (about dataflow). i want to move to new converstaion because this is getting too big. please tell me what to prompt the new conversation"
    label: "important - new conversation"

  - trigger: ":instruct"
    replace: "I have a homework question about LR parsing that I need to solve. I want to work through it using the same methodology we used successfully before: Go very slowly, step by step. Don't move to the next step until I explicitly approve with yes or continue Use multiple concrete examples to explain concepts If I say that I don't understand, completely restart the explanation from a simpler level. Explain technical terms in plain language first before using them"

    label: "important - full instructions"

  - trigger: ":can"
    replace: "can you teach it to me very slowly and comprehensively. move in small steps and only move on after i confimred"
    label: "important - can you teach it to me very slowly and comprehensively"
  # File and Code Management
  - trigger: ":copyable"
    replace: "show the filename in copyable block"
    label: "show the filename in copyable block"

  - trigger: ":struct"
    replace: "provide a command for creating the file structure\n"
    label: "provide a command for creating the file structure"

  - trigger: ":empty"
    replace: "provide command for creating the empty files"
    label: "empty files"

  - trigger: ":show"
    replace: "provide with a command to show you all files (copy it to my clipboard)"
    label: "show you"

  # Modifications and Details
  - trigger: ":imagine"
    replace: "but dont use the 'imagine' thing"
    label: "imagine"

  - trigger: ":modi"
    replace: "dont make any unnecessary modifications"
    label: "modi"

  - trigger: ":det"
    replace: "make it more detailed"
    label: "make it more detailed"

  - trigger: ":di"
    replace: "don't implement yet. let's discuss it first"
    label: "don't implement yet"

  # Process and Flow
  - trigger: ":inc"
    replace: "let's start with {} and proceed from there very slowly.\nmade the least amount of modifications each step"
    label: "incremental flow"

  - trigger: ":pr"
    replace: "let's proceed"
    label: "let's proceed"

  - trigger: ":br"
    replace: "brainstorm some ideas first"
    label: "brainstorm some ideas first"

  # Comparisons and Technical
  - trigger: ":wd"
    replace: "what's the difference"
    label: "what's the difference"

  - trigger: ":dif"
    replace: "difference"
    label: "difference"

  - trigger: ":ana"
    replace: "don't use analogies. i want to understand in the most technical sense."
    label: "analogies"
