# Host shortcuts

matches:
  - trigger: ":ytreex"
    replace: "yuval@treex-dev-tlv"

  - trigger: ":j00"
    replace: "jetson0.local"
    label: "jetson0"

  - trigger: ":y0"
    replace: "yuvalspiegel@yuvals-MacBook-Pro-5.local"
    label: "yuvals macbook"

  - regex: ':j(?P<i>0[1-9]|[1-9][0-9])'
    replace: "jetson{{i}}.local"
    label: "jetson host"

  - trigger: ":fm1"
    replace: "fm1.local"
    label: "fm1"

  - trigger: ":fm2"
    replace: "fm2.local"
    label: "fm2"

  - trigger: ":fm3"
    replace: "fm3.local"
    label: "fm3"

  - trigger: ":fm4"
    replace: "fm4.local"
    label: "fm4"

  - trigger: ":p0"
    replace: "~/treex-mono/robopilot/yolo-playground/data/jetson-results/"
