# Host shortcuts

matches:
  - trigger: ":j00"
    replace: "jetson0.local"
    label: "jetson0"

  - trigger: ":y0"
    replace: "yuvalspiegel@yuvals-MacBook-Pro-5.local"
    label: "yuvals macbook"

  - trigger: ":j01"
    replace: "jetson1.local"
    label: "jetson1"

  - trigger: ":j02"
    replace: "jetson2.local"
    label: "jetson2"

  - trigger: ":j03"
    replace: "jetson3.local"
    label: "jetson3"

  - trigger: ":j04"
    replace: "jetson4.local"
    label: "jetson4"

  - trigger: ":j05"
    replace: "jetson5.local"
    label: "jetson5"

  - trigger: ":j06"
    replace: "jetson6.local"
    label: "jetson6"

  - trigger: ":j07"
    replace: "jetson7.local"
    label: "jetson7"

  - trigger: ":j08"
    replace: "jetson8.local"
    label: "jetson8"

  - trigger: ":j09"
    replace: "jetson9.local"
    label: "jetson9"

  - trigger: ":j10"
    replace: "jetson10.local"
    label: "jetson10"

  - trigger: ":j11"
    replace: "jetson11.local"
    label: "jetson11"

  - trigger: ":j12"
    replace: "jetson12.local"
    label: "jetson12"

  - trigger: ":j13"
    replace: "jetson13.local"
    label: "jetson13"

  - trigger: ":j14"
    replace: "jetson14.local"
    label: "jetson14"

  - trigger: ":j15"
    replace: "jetson15.local"
    label: "jetson15"

  - trigger: ":j16"
    replace: "jetson16.local"
    label: "jetson16"

  - trigger: ":j17"
    replace: "jetson17.local"
    label: "jetson17"

  - trigger: ":j18"
    replace: "jetson18.local"
    label: "jetson18"

  - trigger: ":j19"
    replace: "jetson19.local"
    label: "jetson19"

  - trigger: ":j20"
    replace: "jetson20.local"
    label: "jetson20"

  - trigger: ":j21"
    replace: "jetson21.local"
    label: "jetson21"

  - trigger: ":j22"
    replace: "jetson22.local"
    label: "jetson22"

  - trigger: ":j23"
    replace: "jetson23.local"
    label: "jetson23"

  - trigger: ":j24"
    replace: "jetson24.local"
    label: "jetson24"

  - trigger: ":j25"
    replace: "jetson25.local"
    label: "jetson25"

  - trigger: ":j26"
    replace: "jetson26.local"
    label: "jetson26"

  - trigger: ":j27"
    replace: "jetson27.local"
    label: "jetson27"

  - trigger: ":j28"
    replace: "jetson28.local"
    label: "jetson28"

  - trigger: ":j29"
    replace: "jetson29.local"
    label: "jetson29"

  - trigger: ":j30"
    replace: "jetson30.local"
    label: "jetson30"

  - trigger: ":j31"
    replace: "jetson31.local"
    label: "jetson31"

  - trigger: ":j32"
    replace: "jetson32.local"
    label: "jetson32"

  - trigger: ":j33"
    replace: "jetson33.local"
    label: "jetson33"

  - trigger: ":j34"
    replace: "jetson34.local"
    label: "jetson34"

  - trigger: ":j35"
    replace: "jetson35.local"
    label: "jetson35"

  - trigger: ":j36"
    replace: "jetson36.local"
    label: "jetson36"

  - trigger: ":j37"
    replace: "jetson37.local"
    label: "jetson37"

  - trigger: ":j38"
    replace: "jetson38.local"
    label: "jetson38"

  - trigger: ":j39"
    replace: "jetson39.local"
    label: "jetson39"

  - trigger: ":j40"
    replace: "jetson40.local"
    label: "jetson40"

  - trigger: ":j41"
    replace: "jetson41.local"
    label: "jetson41"

  - trigger: ":j42"
    replace: "jetson42.local"
    label: "jetson42"

  - trigger: ":j43"
    replace: "jetson43.local"
    label: "jetson43"

  - trigger: ":j44"
    replace: "jetson44.local"
    label: "jetson44"

  - trigger: ":j45"
    replace: "jetson45.local"
    label: "jetson45"

  - trigger: ":j46"
    replace: "jetson46.local"
    label: "jetson46"

  - trigger: ":j47"
    replace: "jetson47.local"
    label: "jetson47"

  - trigger: ":j48"
    replace: "jetson48.local"
    label: "jetson48"

  - trigger: ":j49"
    replace: "jetson49.local"
    label: "jetson49"

  - trigger: ":j50"
    replace: "jetson50.local"
    label: "jetson50"

  - trigger: ":j51"
    replace: "jetson51.local"
    label: "jetson51"

  - trigger: ":j52"
    replace: "jetson52.local"
    label: "jetson52"

  - trigger: ":j53"
    replace: "jetson53.local"
    label: "jetson53"

  - trigger: ":j54"
    replace: "jetson54.local"
    label: "jetson54"

  - trigger: ":j55"
    replace: "jetson55.local"
    label: "jetson55"

  - trigger: ":j56"
    replace: "jetson56.local"
    label: "jetson56"

  - trigger: ":j57"
    replace: "jetson57.local"
    label: "jetson57"

  - trigger: ":j58"
    replace: "jetson58.local"
    label: "jetson58"

  - trigger: ":j59"
    replace: "jetson59.local"
    label: "jetson59"

  - trigger: ":j60"
    replace: "jetson60.local"
    label: "jetson60"

  - trigger: ":j61"
    replace: "jetson61.local"
    label: "jetson61"

  - trigger: ":j62"
    replace: "jetson62.local"
    label: "jetson62"

  - trigger: ":j63"
    replace: "jetson63.local"
    label: "jetson63"

  - trigger: ":j64"
    replace: "jetson64.local"
    label: "jetson64"

  - trigger: ":j65"
    replace: "jetson65.local"
    label: "jetson65"

  - trigger: ":j66"
    replace: "jetson66.local"
    label: "jetson66"

  - trigger: ":j67"
    replace: "jetson67.local"
    label: "jetson67"

  - trigger: ":j68"
    replace: "jetson68.local"
    label: "jetson68"

  - trigger: ":j69"
    replace: "jetson69.local"
    label: "jetson69"

  - trigger: ":j70"
    replace: "jetson70.local"
    label: "jetson70"

  - trigger: ":j71"
    replace: "jetson71.local"
    label: "jetson71"

  - trigger: ":j72"
    replace: "jetson72.local"
    label: "jetson72"

  - trigger: ":j73"
    replace: "jetson73.local"
    label: "jetson73"

  - trigger: ":j74"
    replace: "jetson74.local"
    label: "jetson74"

  - trigger: ":j75"
    replace: "jetson75.local"
    label: "jetson75"

  - trigger: ":j76"
    replace: "jetson76.local"
    label: "jetson76"

  - trigger: ":j77"
    replace: "jetson77.local"
    label: "jetson77"

  - trigger: ":j78"
    replace: "jetson78.local"
    label: "jetson78"

  - trigger: ":j79"
    replace: "jetson79.local"
    label: "jetson79"

  - trigger: ":j80"
    replace: "jetson80.local"
    label: "jetson80"

  - trigger: ":j81"
    replace: "jetson81.local"
    label: "jetson81"

  - trigger: ":j82"
    replace: "jetson82.local"
    label: "jetson82"

  - trigger: ":j83"
    replace: "jetson83.local"
    label: "jetson83"

  - trigger: ":j84"
    replace: "jetson84.local"
    label: "jetson84"

  - trigger: ":j85"
    replace: "jetson85.local"
    label: "jetson85"

  - trigger: ":j86"
    replace: "jetson86.local"
    label: "jetson86"

  - trigger: ":j87"
    replace: "jetson87.local"
    label: "jetson87"

  - trigger: ":j88"
    replace: "jetson88.local"
    label: "jetson88"

  - trigger: ":j89"
    replace: "jetson89.local"
    label: "jetson89"

  - trigger: ":j90"
    replace: "jetson90.local"
    label: "jetson90"

  - trigger: ":j91"
    replace: "jetson91.local"
    label: "jetson91"

  - trigger: ":j92"
    replace: "jetson92.local"
    label: "jetson92"

  - trigger: ":j93"
    replace: "jetson93.local"
    label: "jetson93"

  - trigger: ":j94"
    replace: "jetson94.local"
    label: "jetson94"

  - trigger: ":j95"
    replace: "jetson95.local"
    label: "jetson95"

  - trigger: ":j96"
    replace: "jetson96.local"
    label: "jetson96"

  - trigger: ":j97"
    replace: "jetson97.local"
    label: "jetson97"

  - trigger: ":j98"
    replace: "jetson98.local"
    label: "jetson98"

  - trigger: ":j99"
    replace: "jetson99.local"
    label: "jetson99"

  - trigger: ":fm1"
    replace: "fm1.local"
    label: "fm1"

  - trigger: ":fm2"
    replace: "fm2.local"
    label: "fm2"

  - trigger: ":fm3"
    replace: "fm3.local"
    label: "fm3"

  - trigger: ":fm4"
    replace: "fm4.local"
    label: "fm4"

  - trigger: ":p0"
    replace: "~/treex-mono/robopilot/yolo-playground/data/jetson-results/"
