# Host shortcuts

matches:
  - trigger: ":j0"
    replace: "yuval@treex-dev-tlv"
    label: "treex-dev-tlv"

  - trigger: ":y0"
    replace: "yuvalspiegel@yuvals-MacBook-Pro-5.local"
    label: "yuvals macbook"

  - trigger: ":j2"
    replace: "jetson2.local"
    label: "jetson2"

  - trigger: ":j3"
    replace: "jetson3.local"
    label: "jetson3"

  - trigger: ":j4"
    replace: "jetson4.local"
    label: "jetson4"

  - trigger: ":j5"
    replace: "jetson5.local"
    label: "jetson5"

  - trigger: ":j6"
    replace: "jetson6.local"
    label: "jetson6"

  - trigger: ":j7"
    replace: "jetson7.local"
    label: "jetson7"

  - trigger: ":j8"
    replace: "jetson8.local"
    label: "jetson8"

  - trigger: ":j9"
    replace: "jetson9.local"
    label: "jetson9"

  - trigger: ":j10"
    replace: "jetson10.local"
    label: "jetson10"

  - trigger: ":j11"
    replace: "jetson11.local"
    label: "jetson11"

  - trigger: ":j12"
    replace: "jetson12.local"
    label: "jetson12"

  - trigger: ":j13"
    replace: "jetson13.local"
    label: "jetson13"

  - trigger: ":j14"
    replace: "jetson14.local"
    label: "jetson14"

  - trigger: ":j15"
    replace: "jetson15.local"
    label: "jetson15"

  - trigger: ":p0"
    replace: "~/treex-mono/robopilot/yolo-playground/data/jetson-results/"
