return {
  -- "nvim-neotest/neotest",
  -- dependencies = {
  --   "nvim-lua/plenary.nvim",
  --   "antoinemadec/FixCursorHold.nvim",
  --   "nvim-treesitter/nvim-treesitter",
  --   "nvim-neotest/nvim-nio",
  -- },
  -- event = "BufReadPost", -- Load when a file is opened
  -- cmd = {
  --   "Neotest",
  -- },
  -- config = function()
  --   require("neotest").setup({
  --     -- Add your neotest configuration here
  --     adapters = {
  --       require("neotest-python")({
  --         dap = { justMyCode = false },
  --       }),
  --       -- Add other adapters as needed
  --     },
  --     -- Add any other neotest options here
  --   })
  -- end,
  -- keys = {
  --   { "<leader>tt", function() require("neotest").run.run() end, desc = "Run nearest test" },
  --   { "<leader>tf", function() require("neotest").run.run(vim.fn.expand("%")) end, desc = "Run current file" },
  --   { "<leader>td", function() require("neotest").run.run({strategy = "dap"}) end, desc = "Debug nearest test" },
  --   { "<leader>ts", function() require("neotest").run.stop() end, desc = "Stop nearest test" },
  --   { "<leader>ta", function() require("neotest").run.attach() end, desc = "Attach to nearest test" },
  -- },
}
