return {
  -- { -- Linting
  --   'mfussenegger/nvim-lint',
  --   event = { 'BufReadPre', 'BufNewFile' },
  --   config = function()
  --     local lint = require 'lint'
  --     lint.linters_by_ft = {
  --       markdown = { 'markdownlint' },
  --       python = {}, -- Add ruff and mypy here
  --       go = { 'golangci_lint' }, -- Add this line for Golang
  --     }
  --
  --     local lint_augroup = vim.api.nvim_create_augroup('lint', { clear = true })
  --     vim.api.nvim_create_autocmd({ 'BufEnter', 'BufWritePost', 'InsertLeave' }, {
  --       group = lint_augroup,
  --       callback = function()
  --         lint.try_lint()
  --       end,
  --     })
  --   end,
  -- },
}
