-- lua/plugins/oil.lua
return {
  -- 'stevearc/oil.nvim',
  -- cmd = 'Oil',
  -- keys = {
  --   { '-', '<CMD>Oil<CR>', desc = 'Open parent directory' },
  -- },
  -- opts = {
  --   -- Your oil.nvim options here
  --   -- For example:
  --   -- default_file_explorer = true,
  --   -- skip_confirm_for_simple_edits = false,
  --   -- prompt_save_on_select_new_entry = true,
  -- },
  -- dependencies = {
  --   {
  --     'echasnovski/mini.icons',
  --     lazy = true,
  --     opts = {},
  --   },
  -- },
  -- config = function(_, opts)
  --   require('oil').setup(opts)
  -- end,
}
