#:schema https://raw.githubusercontent.com/insanum/gcalcli/HEAD/data/config-schema.json

[calendars]
default-calendars = [
  "yuval#green",
  "studies#magenta",
  "therapy#cyan",
  "hw#red",
  "meetings#blue",
  "חגים בישראל#white",
]

ignore-calendars = ["Sport#brown"]

[colors]
owner = "blue"
reader = "cyan"

[output]
week-start = "sunday"
